### ISSUE TITLE
Can a custom init function be added to `NavigationControllerStep` & `TabBarControllerStep`?

### ISSUE THREAD

**Issue by wwdc14** [ekazaev/route-composer#74]
I have a `CustomNavigationController` must be call custom init function, but `NavigationControllerStep` does not provide custom initialization. Now i have to Now I have to re-instantiate `SingleContainerStep` to use the custom initialization function

Or you can set the access permission of `NavigationControllerStep` to open. I can override it.

Do you have any good ideas?

**Comment by ekazaev** [comment]
@wwdc14 Hi
I see your point but technically this is exactly what is `SingleContainerStep` for and this is expected. Because you can be not happy with the factory or a finder there. So `SingleContainerStep` step allows you to configure both of them the way you want. 
I am very against any inheritance it this case, so I reserved it to be used only within the library. 
If you want to be able to write your `SingleContainerStep` by calling just one instance just wrap it in to a function like this:

```
func MyNavigationControllerStep<C>(parameters: Whatever) -> SingleContainerStep<NilFinder<ExampleNavigationController, C>, NavigationControllerFactory<ExampleNavigationController, C>> {
    return SingleContainerStep(finder: NilFinder(), factory: MyCustomEmapleNavigationControllerFactory<C>(parameters: parameters))
}
```

and then use it like `NavigationControllerStep` with the same purpose:

```
        StepAssembly(Whatever)
            .using(ExampleNavigationController.push())
            .from(MyNavigationControllerStep(parameters: Whatever))
            .using(GeneralAction.presentModally())
            .from(GeneralStep.current())
            .assemble()
```

I assume this is what you want

**Comment by wwdc14** [comment]
Awesome! thanks
